import Phaser from 'phaser';
import type { GameScene } from './GameScene';
import { WORLD, ROADS, PLAZA, BUILDINGS, AREAS, FURNITURE, AREA_LIGHTS, CLUE_SPOTS, NPC_SPOTS, AMBIENT_NPC_SPOTS, BATTERIES, LAMPS, PROPS, EXIT_ROAD, BOOT_TRAIL, Rect } from '../data/world';
import { EVIDENCE } from '../data/evidence';
import { CHARACTERS } from '../data/characters';
import { DEPTH } from '../systems/constants';
import { getState, toast, setState, setMode, journal, setFlag } from '../systems/store';

export function buildWorld(sc: GameScene) {
  const s = getState(); const L = sc.lighting;
  sc.add.image(0, 0, 'ground').setOrigin(0).setDepth(DEPTH.GROUND);
  sc.addWall(-20, -20, WORLD.width + 40, 20); sc.addWall(-20, WORLD.height, WORLD.width + 40, 20); sc.addWall(-20, 0, 20, WORLD.height); sc.addWall(WORLD.width, 0, 20, WORLD.height);
  for (const b of BUILDINGS) { sc.add.image(b.x, b.y - (b.extraTop ?? 0), `bld-${b.id}`).setOrigin(0).setDepth(b.y + b.h); sc.addWall(b.x, b.y, b.w, b.h); L.addOccluder(b.x, b.y, b.w, b.h); for (const wnd of b.litWindows ?? []) L.addLight({ x: wnd.x, y: wnd.y + 8, radius: 36, intensity: 0.45, color: 0xffa040, flicker: 0.004 }); if (b.door === undefined) continue; const dx = b.x + b.door, dy = b.y + b.h; if (b.enter) { L.addLight({ x: dx, y: dy + 2, radius: 34, intensity: 0.5, color: 0xffc070, flicker: 0.01 }); const area = AREAS[b.enter]; sc.addInteractable({ id: `door-${b.id}`, x: dx, y: dy + 4, r: 16, label: `Enter ${b.name}`, action: () => sc.travel(area.id, area.spawn!.x, area.spawn!.y, 'up') }); } else if (b.locked) { const msg = b.locked; sc.addInteractable({ id: `door-${b.id}`, x: dx, y: dy + 4, r: 14, label: 'Knock', action: () => toast(msg, 'thought') }); } }
  for (const l of LAMPS) { sc.add.image(l.x, l.y, l.dead ? 'lamp-dead' : 'lamp').setOrigin(0.5, 1).setDepth(l.y); sc.addWall(l.x - 2, l.y - 3, 4, 3); if (!l.dead) { L.addLight({ x: l.x, y: l.y - 4, radius: 60, intensity: 0.68, color: 0xffb060, flicker: l.flicker ?? 0.004 }); L.addLight({ x: l.x, y: l.y - 40, radius: 12, intensity: 0.65, color: 0xffd090, flicker: l.flicker ?? 0.004, glowScale: 1.6 }); } }
  for (const p of PROPS) { sc.add.image(p.x, p.y, p.key).setOrigin(0.5, 1).setDepth(p.y); if (p.collide) sc.addWall(p.x - p.collide.w / 2, p.y - p.collide.h, p.collide.w, p.collide.h); if (p.examine) { const text = p.examine; sc.addInteractable({ id: `prop-${p.key}-${p.x}`, x: p.x, y: p.y + 2, r: 20, label: 'Examine', action: () => toast(text, 'thought') }); } }
  L.addLight({ x: 460, y: 432, radius: 46, intensity: 0.8, color: 0xff2030, blink: 0.9 }); L.addLight({ x: 480, y: 432, radius: 46, intensity: 0.8, color: 0x2050ff, blink: 0.9, blinkOffset: Math.PI });
  const reserved: { x: number; y: number }[] = [...NPC_SPOTS, ...CLUE_SPOTS, ...BATTERIES, ...LAMPS, ...PROPS, EXIT_ROAD, { x: 548, y: 740 }].filter((p) => p.x < WORLD.width); const hit = (x: number, y: number, r: Rect, m: number) => x > r.x - m && x < r.x + r.w + m && y > r.y - m && y < r.y + r.h + m; const free = (x: number, y: number) => { if (BUILDINGS.some((b) => hit(x, y, { x: b.x, y: b.y - (b.extraTop ?? 0), w: b.w, h: b.h + (b.extraTop ?? 0) }, 14))) return false; if (ROADS.some((r) => hit(x, y, r, 8)) || hit(x, y, PLAZA, 10)) return false; if (hit(x, y, { x: 590, y: 480, w: 90, h: 140 }, 0)) return false; return !reserved.some((p) => Math.hypot(p.x - x, p.y - y) < 30); }; const rand = new Phaser.Math.RandomDataGenerator(['hollowpine']); const placed: { x: number; y: number }[] = []; const plant = (x: number, y: number) => { if (!free(x, y) || placed.some((p) => Math.hypot(p.x - x, p.y - y) < 20)) return; placed.push({ x, y }); const key = rand.pick(['tree-a', 'tree-a', 'tree-b', 'tree-c']); sc.add.image(x, y, key).setOrigin(0.5, 1).setDepth(y); sc.addWall(x - 3, y - 4, 6, 4); }; for (let x = 10; x < WORLD.width; x += 18) { plant(x + rand.between(-4, 4), 26 + rand.between(0, 14)); plant(x + rand.between(-4, 4), WORLD.height - 4 - rand.between(0, 10)); } for (let y = 40; y < WORLD.height; y += 20) { plant(10 + rand.between(0, 12), y); plant(WORLD.width - 10 - rand.between(0, 12), y); } for (let i = 0; i < 500 && placed.length < 150; i++) plant(rand.between(20, WORLD.width - 20), rand.between(40, WORLD.height - 10)); for (let i = 0; i < 12; i++) { const x = rand.between(30, WORLD.width - 30), y = rand.between(60, WORLD.height - 30); if (free(x, y)) sc.add.image(x, y, 'stump').setOrigin(0.5, 1).setDepth(y); }
  for (const n of NPC_SPOTS) { const spr = sc.add.sprite(n.x, n.y, `npc-${n.id}`).setOrigin(0.5, 1).setDepth(n.y); sc.tweens.add({ targets: spr, scaleY: 0.965, duration: 1300 + Math.random() * 500, yoyo: true, repeat: -1, ease: 'Sine.inOut' }); sc.addWall(n.x - 5, n.y - 5, 10, 5); const name = CHARACTERS[n.id].name; sc.addInteractable({ id: `npc-${n.id}`, x: n.x, y: n.y + 2, r: 26, label: `Talk to ${name}`, action: () => sc.startDialogue(n.id) }); if (n.id === 'halvorsen') L.addLight({ x: n.x + 6, y: n.y - 6, radius: 30, intensity: 0.5, color: 0xffc070, flicker: 0.02 }); }
  for (const n of AMBIENT_NPC_SPOTS) { const spr = sc.add.sprite(n.x, n.y, `npc-${n.id}`).setOrigin(0.5, 1).setDepth(n.y).setAlpha(0.72); sc.tweens.add({ targets: spr, x: n.x + (n.id === 'henrik' ? 10 : -10), duration: 2600 + Math.random() * 1800, yoyo: true, repeat: -1, ease: 'Sine.inOut' }); }
  const { from, to, count } = BOOT_TRAIL; const ang = Math.atan2(to.y - from.y, to.x - from.x); for (let i = 0; i < count; i++) { const t = i / (count - 1), side = i % 2 ? 3 : -3, x = from.x + (to.x - from.x) * t - Math.sin(ang) * side, y = from.y + (to.y - from.y) * t + Math.cos(ang) * side; const img = sc.add.image(x, y, 'bootprint').setRotation(ang + Math.PI / 2).setDepth(DEPTH.DECAL).setAlpha(0); sc.hiddenDecals.push(img); }
  sc.addInteractable({ id: 'exit-road', x: EXIT_ROAD.x, y: EXIT_ROAD.y, r: 22, label: 'The road down the mountain', action: () => { if (!getState().flags.met_sheriff) { toast("Not yet. I came up here for a reason. The sheriff's waiting in the square.", 'thought'); return; } setState({ confirm: { title: 'Leave Hollowpine?', text: 'The last chained bus is idling at the switchback. If you board it, the case goes cold with the town.', action: 'leave' } }); setMode('confirm'); }); }
