import Phaser from 'phaser';
import type { GameScene } from './GameScene';
import { WORLD, ROADS, PLAZA, BUILDINGS, AREAS, FURNITURE, AREA_LIGHTS, CLUE_SPOTS, NPC_SPOTS, AMBIENT_NPC_SPOTS, BATTERIES, LAMPS, PROPS, EXIT_ROAD, BOOT_TRAIL, Rect } from '../data/world';
import { EVIDENCE } from '../data/evidence'; import { CHARACTERS } from '../data/characters'; import { DEPTH } from '../systems/constants'; import { getState, toast, setState, setMode, journal, setFlag } from '../systems/store';
export function buildWorld(sc:GameScene){ const s=getState(),L=sc.lighting; sc.add.image(0,0,'ground').setOrigin(0).setDepth(DEPTH.GROUND); sc.addWall(-20,-20,WORLD.width+40,20);sc.addWall(-20,WORLD.height,WORLD.width+40,20);sc.addWall(-20,0,20,WORLD.height);sc.addWall(WORLD.width,0,20,WORLD.height);
for(const b of BUILDINGS){sc.add.image(b.x,b.y-(b.extraTop??0),`bld-${b.id}`).setOrigin(0).setDepth(b.y+b.h);sc.addWall(b.x,b.y,b.w,b.h);L.addOccluder(b.x,b.y,b.w,b.h);if(b.door===undefined)continue;const dx=b.x+b.door,dy=b.y+b.h;if(b.enter){L.addLight({x:dx,y:dy+2,radius:34,intensity:.5,color:0xffc070,flicker:.01});const a=AREAS[b.enter];sc.addInteractable({id:`door-${b.id}`,x:dx,y:dy+4,r:16,label:`Enter ${b.name}`,action:()=>sc.travel(a.id,a.spawn!.x,a.spawn!.y,'up')});}else if(b.locked)sc.addInteractable({id:`door-${b.id}`,x:dx,y:dy+4,r:14,label:'Knock',action:()=>toast(b.locked!,'thought')});}
for(const l of LAMPS){sc.add.image(l.x,l.y,l.dead?'lamp-dead':'lamp').setOrigin(.5,1).setDepth(l.y);sc.addWall(l.x-2,l.y-3,4,3);if(!l.dead){L.addLight({x:l.x,y:l.y-4,radius:60,intensity:.68,color:0xffb060,flicker:l.flicker??.004});L.addLight({x:l.x,y:l.y-40,radius:12,intensity:.65,color:0xffd090,flicker:l.flicker??.004,glowScale:1.6});}}
for(const p of PROPS){sc.add.image(p.x,p.y,p.key).setOrigin(.5,1).setDepth(p.y);if(p.collide)sc.addWall(p.x-p.collide.w/2,p.y-p.collide.h,p.collide.w,p.collide.h);if(p.examine)sc.addInteractable({id:`prop-${p.key}-${p.x}`,x:p.x,y:p.y+2,r:20,label:'Examine',action:()=>toast(p.examine!,'thought')});}
L.addLight({x:460,y:432,radius:46,intensity:.8,color:0xff2030,blink:.9});L.addLight({x:480,y:432,radius:46,intensity:.8,color:0x2050ff,blink:.9,blinkOffset:Math.PI});
const tape=sc.add.graphics().setDepth(DEPTH.DECAL+1),tr={x:598,y:326,w:64,h:52};for(let x=tr.x;x<tr.x+tr.w;x+=6){tape.fillStyle((x/6)%2?0xe8c020:0x1a1a1a,1);tape.fillRect(x,tr.y+tr.h,6,1);tape.fillRect(x,tr.y,6,1);}for(let y=tr.y;y<tr.y+tr.h;y+=6){tape.fillStyle((y/6)%2?0xe8c020:0x1a1a1a,1);tape.fillRect(tr.x,y,1,6);tape.fillRect(tr.x+tr.w,y,1,6);}sc.add.image(624,354,'body').setOrigin(.5,1).setDepth(354);sc.addWall(612,344,24,8);sc.addInteractable({id:'body',x:624,y:358,r:9,label:'Examine: Mara Linden',action:()=>{toast('Mara Linden. Eyes open, lashes white with frost. No blood. No struggle.','thought');setFlag('examined_body');journal('Examined the body.');}});
const {from,to,count}=BOOT_TRAIL,ang=Math.atan2(to.y-from.y,to.x-from.x);for(let i=0;i<count;i++){const t=i/(count-1),side=i%2?3:-3,x=from.x+(to.x-from.x)*t-Math.sin(ang)*side,y=from.y+(to.y-from.y)*t+Math.cos(ang)*side;sc.hiddenDecals.push(sc.add.image(x,y,'bootprint').setRotation(ang+Math.PI/2).setDepth(DEPTH.DECAL).setAlpha(0));}
const reserved:any[]=[...NPC_SPOTS,...CLUE_SPOTS,...BATTERIES,...LAMPS,...PROPS,EXIT_ROAD,{x:548,y:740}];const hit=(x:number,y:number,r:Rect,m:number)=>x>r.x-m&&x<r.x+r.w+m&&y>r.y-m&&y<r.y+r.h+m;const free=(x:number,y:number)=>!BUILDINGS.some(b=>hit(x,y,{x:b.x,y:b.y,w:b.w,h:b.h},14))&&!ROADS.some(r=>hit(x,y,r,8))&&!hit(x,y,PLAZA,10)&&!reserved.some(p=>Math.hypot(p.x-x,p.y-y)<30);const rand=new Phaser.Math.RandomDataGenerator(['hollowpine']),placed:any[]=[];for(let i=0;i<280&&placed.length<120;i++){const x=rand.between(20,WORLD.width-20),y=rand.between(40,WORLD.height-10);if(free(x,y)&&!placed.some(p=>Math.hypot(p.x-x,p.y-y)<20)){placed.push({x,y});sc.add.image(x,y,rand.pick(['tree-a','tree-a','tree-b','tree-c'])).setOrigin(.5,1).setDepth(y);sc.addWall(x-3,y-4,6,4);}}
sc.addInteractable({id:'exit-road',x:EXIT_ROAD.x,y:EXIT_ROAD.y,r:22,label:'The road down the mountain',action:()=>{if(!getState().flags.met_sheriff){toast("Not yet. The sheriff's waiting in the square.",'thought');return;}setState({confirm:{title:'Leave Hollowpine?',text:'The last chained bus is idling at the switchback.',action:'leave'}});setMode('confirm');}});
for(const a of Object.values(AREAS)){if(!a.indoor)continue;const b=a.bounds,cx=b.x+b.w/2;sc.add.rectangle(b.x-500,b.y-500,b.w+1000,b.h+1000,0x060910).setOrigin(0).setDepth(DEPTH.GROUND-1);sc.add.tileSprite(b.x,b.y,b.w,b.h,a.floor!).setOrigin(0).setDepth(DEPTH.GROUND);sc.add.tileSprite(b.x,b.y,b.w,28,a.wall!).setOrigin(0).setDepth(b.y+28);sc.add.image(cx,b.y+b.h-4,'doormat').setDepth(DEPTH.DECAL);sc.addWall(b.x,b.y,b.w,30);sc.addWall(b.x-6,b.y,6,b.h+6);sc.addWall(b.x+b.w,b.y,6,b.h+6);sc.addInteractable({id:`exit-${a.id}`,x:cx,y:b.y+b.h-2,r:18,label:'Step outside',action:()=>sc.travel('town',a.exit!.x,a.exit!.y,'down')});L.addLight({x:cx,y:b.y+b.h+4,radius:40,intensity:.35,color:0x6a8ad0});}
for(const f of FURNITURE){const b=AREAS[f.area].bounds,x=b.x+f.x,y=b.y+f.y,img=sc.add.image(x,y,f.key).setOrigin(0);img.setDepth(f.key==='rug'?DEPTH.DECAL:y+img.height);if(f.collide)sc.addWall(x+1,y+img.height*.45,img.width-2,img.height*.55);if(f.occlude)L.addOccluder(x+1,y+img.height*.45,img.width-2,img.height*.55);if(f.light)L.addLight({x:x+f.light.dx,y:y+f.light.dy,radius:f.light.radius,intensity:f.light.intensity,color:f.light.color,flicker:f.light.flicker});}for(const l of AREA_LIGHTS){const b=AREAS[l.area].bounds;L.addLight({x:b.x+l.x,y:b.y+l.y,radius:l.radius,intensity:l.intensity,color:l.color,flicker:l.flicker});}
for(const c of CLUE_SPOTS){if(s.evidence.includes(c.id))continue;const ev=EVIDENCE[c.id],img=sc.add.image(c.x,c.y,`ev-${c.id}`).setScale(.5).setDepth(c.y+1);if(ev.hidden)img.setAlpha(0);const it=sc.addInteractable({id:`clue-${c.id}`,x:c.x,y:c.y,r:14,label:`Examine: ${c.label}`,hidden:ev.hidden,sprite:img,action:()=>{it.active=false;img.destroy();sc.onEvidenceFound(c.id);}});}
for(const n of NPC_SPOTS){const spr=sc.add.sprite(n.x,n.y,`npc-${n.id}`).setOrigin(.5,1).setDepth(n.y);sc.tweens.add({targets:spr,scaleY:.965,duration:1500,yoyo:true,repeat:-1});sc.addWall(n.x-5,n.y-5,10,5);const name=CHARACTERS[n.id].name;sc.addInteractable({id:`npc-${n.id}`,x:n.x,y:n.y+2,r:26,label:`Talk to ${name}`,action:()=>sc.startDialogue(n.id)});}
for(const n of AMBIENT_NPC_SPOTS){const spr=sc.add.sprite(n.x,n.y,`npc-${n.id}`).setOrigin(.5,1).setDepth(n.y).setAlpha(.72);sc.tweens.add({targets:spr,x:n.x+(n.id==='henrik'?10:-10),duration:2800,yoyo:true,repeat:-1,ease:'Sine.inOut'});}
for(const bt of BATTERIES){if(s.pickups.includes(bt.id))continue;const img=sc.add.image(bt.x,bt.y,'battery').setOrigin(.5,1).setDepth(bt.y),it=sc.addInteractable({id:`bat-${bt.id}`,x:bt.x,y:bt.y,r:14,label:'Pick up battery',action:()=>{it.active=false;img.destroy();sc.onBattery(bt.id);}});sc.tweens.add({targets:img,y:bt.y-2,duration:900,yoyo:true,repeat:-1});}}
